### ISSUE TITLE
Add ComponentsTab placeholder under RepoPage

### ISSUE THREAD

**Issue by JerrySentry** [codecov/engineering-team#1370]
Design doc: https://www.figma.com/file/lpCAamL0oUGKvVng0g7vex/GH-234?type=design&node-id=1-2&mode=design&t=9bBDzCMR6WmyCZZ8-0

1. Copy everything from FlagsTab under RepoPage for this, change the following from Flags to Components:
    - static texts
    - file names
    - function names (except still use `useActivateFlagMeasurements` and keep function calls outside of the ComponentsTab to be the same, we will do that later)

2. Basically at the end this new table shows and functions the same way as FlagsTab except everything is showing as Components and in the code the only `useRepoBackfillingStatus` it is fetching from Flags

3. Request new asset for blurredTable.png

4. Make sure FlagsTab is not actually showing in the RepoPage (only show internally via Feature Flag)
5. Request Components Tab feedback https://github.com/codecov/feedback/issues/27
```[tasklist]
### Blocked By
- [ ] https://github.com/codecov/engineering-team/issues/1383
```

**Comment by RulaKhaled** [comment]
- Let's ask marketing for blurredTable.png
- Let's attach design links to all subtasks that requires client changes 
- Add a Note: Change and Last updated are two new columns that need to be added here
- Confirm the expected sorting functionality
  - does icon exist in our icons library?
  - is the goal to introduce the new sorting functionality with this new table (push for no since this needs investigation)
  - what columns are we looking to sort?

**Comment by JerrySentry** [comment]
- Added PNG file request
- Added design link
- Change column is equivalent to the Trend column of flags, should just be a text rename
- Last updated we will add later in this ticket https://github.com/codecov/engineering-team/issues/1380
- Sorting is a good point, that'll require a decent amount of work on both frontend and backend. Will try to push for no
