### ISSUE TITLE
The UI and PR comment are out of sync

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#1614]
**Describe the bug**
The coverage on HEAD% is out of sync on PR comment (98.29%) and the UI (98.30%).

PR example: https://github.com/getsentry/sentry/pull/68889
UI example: https://app.codecov.io/gh/getsentry/sentry/pull/68889?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=getsentry

![image (10)](https://github.com/codecov/engineering-team/assets/152432831/5389ee55-0ca0-4c25-a545-a1e6ae1e604a)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1705
```

**Comment by Adal3n3** [comment]
@trent-codecov can you check out this out of sync issue?

**Comment by tnt-sentry** [comment]
@michelletran-codecov pair up with @giovanni-guidini to get some context/tips on how to dive into these type of problems.

**Comment by michelletran-sentry** [comment]
OK, writing up some investigations, as there seems to be a few moving pieces (and writing this down will keep it organized):
* for the report commit coverage, it looks like `worker` is rounding _down_ the coverage results. This aligns with [what the repos have configured in their YAML](https://docs.codecov.com/docs/codecovyml-reference#coverageround), which is that they're not defined and use the default of rounding `down`. However, looking at the code for how the rounding is done in `worker`, it looks like the _default_ is [ROUND_HALF_EVEN](https://github.com/codecov/worker/blob/5c7c8927010514c2e53f1b14728a57de9be3d102/services/yaml/reader.py#L42). I have not located an override in the code so far to round down by default (so I'm still not sure why it's rounding down currently).
* in the API, the coverage data comes from the report stored in the database (specifically the `commits` table). The `commits` table stores the coverage as a percent with 5 decimal places (i.e. '89.12345'). It is being rounded with [the in-built python `round` to 2 decimal places](https://github.com/codecov/codecov-api/blob/8a02e67e0361426a3ac3e60c9f0c8e4601d4bca1/api/shared/commit/serializers.py#L18). The behaviour of `round` behaves _almost_ like `ROUND_HALF_EVEN`, except for an [exception mentioned in the docs](https://docs.python.org/3/library/functions.html#round).

I'm going to look into the rounding in `worker` again to see if it's _actually_ rounding down as documented. I will also want some clarification on whether the API should show the coverage as specified in the YAML (default to rounding down) and will see if it's low effort to do it (I suspect that parsing the yaml might be expensive? which will be OK in the worker, but maybe less acceptable when loading on a webpage. I'll have to verify). We probably _should_ get away from using Python's default rounding though, because it's not as accurate as using `Decimal`.

**Comment by michelletran-sentry** [comment]
It appears that the YAML is persisted to the `repos` model ([shared ref to Django Model](https://github.com/codecov/shared/blob/f66cce64af17b3516f6a6dc5ad374e976d3ff40c/shared/django_apps/core/models.py#L122), [worker ref to SQLAlchemy model ](https://github.com/codecov/worker/blob/5c7c8927010514c2e53f1b14728a57de9be3d102/database/models/core.py#L68)). So, we can try to load the yaml from DB instead of fetching and parsing. `worker` tries to update the `yaml` referenced [here](https://github.com/codecov/worker/blob/5c7c8927010514c2e53f1b14728a57de9be3d102/services/yaml/__init__.py#L116).

Given that the model is replicated in `shared`, `codecov-api` should be able to query and access that for updated rounding logic.

**Comment by michelletran-sentry** [comment]
Doing more investigation, the coverage data is denormalized into the `report_reportleveltotals` table, which stores the coverage data as `numeric(7, 2)` (truncates the decimal to 2 places). It looks like the API queries this table for the coverage data, rather than accessing it via the `commit` object (it's stored as JSON there). We may have to a migrate the table to increase precision (or maybe figure out if there's a way to use user/repo configured rounding when storing?). I think this would be preferable to parsing the report totals from the `commit` object.

**Comment by michelletran-sentry** [comment]
Everything is merged and the migration has been completed. Will close out this ticket.
