### ISSUE TITLE
Add messaging for user in delinquency status (banner in UI)

### ISSUE THREAD

**Issue by ajay-sentry** [codecov/engineering-team#1814]
When a payment failed, we can have a banner place in the UI.
![Screenshot 2024-05-30 at 2 20 41 PM](https://github.com/codecov/engineering-team/assets/152432831/80437c40-1dc5-4b2f-96bc-7b674eb8a879)

Making a note here: conversation with @ajay-sentry 

- Stripe has like 47 payment failed scenarios https://docs.stripe.com/declines/codes#stripe-decline-codes
- The plan is first we use the messaging "Your last card didn't seem to support our transactions :disappointed: " "Please try a different one this time and unlock the power of Codecov!" This will allow us to cover most of the failures, like transaction_not_allowed, insufficient_funds, etc
- At the meantime we work on storing the most recent failure reason so we don't need to rely on stripe's API all the time.
   - will need Platform team create DB 
   
 Figma: [link](https://www.figma.com/design/QTZQFzluTazvz5fxT0gNdG/GH-1814?node-id=1-2)

**Comment by Adal3n3** [comment]
@ajay-sentry Can I have the list of payment failed reasons from Stripe so I can provide the list of error banners.

**Comment by Adal3n3** [comment]
Here is the design: Figma [link](https://www.figma.com/design/QTZQFzluTazvz5fxT0gNdG/GH-1814?node-id=1-2)
- Currently, the owner table has a "true" or "false" value if their last payment failed or not. We could push a generic payment failed error banner as a first step for now. 
- Based on the data on Stripe, we know the common payment failed due to insufficient_funds, [do_not_honor](https://docs.stripe.com/declines/codes#stripe-decline-codes), Transaction_not_allowed and generic_decline so trying a different card could be a right solution for most customers.
- Please create or use component for this banner.
![Screenshot 2024-06-03 at 2 51 43 PM](https://github.com/codecov/engineering-team/assets/152432831/4c584ff2-42ce-4df0-8435-0536ed318e4a)

**Comment by Adal3n3** [comment]
This is the latest banner, we want to use.
![Screenshot 2024-06-04 at 1 15 58 PM](https://github.com/codecov/engineering-team/assets/152432831/df97e3d6-de23-45a7-80c3-e2a70a2c5e86)
