### ISSUE TITLE
Trigger an error message if the PR didn't update due to Codecov processing issue

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#2218]
This is related to issue https://github.com/codecov/internal-issues/issues/670

We need an error message and maybe a banner in the doc?

Error scenario: 
- when the PR didn't update automatically, 
- setup is correct, 
- the test results uploads are working fine.

Surface Codecov hits a processing issue

What can we tell the user do to try resolving this issue?

**Comment by Adal3n3** [comment]
@rohan-at-sentry @ajay-sentry I'm not sure how this will look like in the UI, do we need a UI banner?

**Comment by rohan-at-sentry** [comment]
If this for TA, i'm not sure of an elegant way to surface this on the UI since error will be on a commit level.  From what we know about the types of failures we've seen from the TA rollout

- Comment doesn't clear because of an issue with the processing pipeline not picking up the right no of builds
- Comment doesn't clear because of an issue with the processing pipeline just failing sometimes

These issues also impact coverage (and impact TA because they share the same notify task). At a minimum we should surface a message on the PR comment.
