### ISSUE TITLE
Identify and move 2-5 models

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#2304]
Decide on the first batch of models and migrate them.

https://github.com/codecov/engineering-team/issues/1019

**Comment by michelletran-sentry** [comment]
Instead of migrating models, I think the better approach would be to migrate each task off using SQLAlchemy models. I've taken an inventory of the tasks and have created a [spreadsheet](https://docs.google.com/spreadsheets/d/1VRXe7T1F_juTZoZrsHzc2kUnRkg5tyThS0k88uCbdq8/edit?usp=sharing) and [call tree](https://www.notion.so/sentry/Worker-Topology-47d26a4090ea4193afd9d6e5c4999fd7?pvs=4) for the tasks. 

My _feeling_ is that the tasks further down the chain (i.e. the leaves) are going to be easier to migrate, so we can start with those. The various `Upload*` tasks, as well as Notify task are probably big and risky, so those would need more care.

**Comment by tnt-sentry** [comment]
Not using this approach
