### ISSUE TITLE
Investigate adding typing to info.context

### ISSUE THREAD

**Issue by suejung-sentry** [codecov/engineering-team#2875]

**Comment by JerrySentry** [comment]
I spent a day trying to find the best approach for this, couldn't see any intuitive way of doing this, mainly the only option is working around a `typing.TypedDict` sort of thing. Had a couple of somewhat working implementations:

Option 1: can easily trace what the `info.context` structure is, but will have to refactor every single resolver to be `info.context` -> `context` and add `context: ContextDict = info.context`
```

# some lib file location

from typing import TypedDict

class ContextDict(TypedDict):
    commit: Commit
    ...

# resolvers file

from lib import ContextDict

@commit_bundle_analysis_bindable.field("bundleAnalysisReport")
def resolve_commit_bundle_analysis_report(commit: Commit, info: GraphQLResolveInfo) -> BundleAnalysisReport:
    context: ContextDict = info.context

    bundle_analysis_report = load_bundle_analysis_report(commit)

    # Store the created SQLite DB path in info.context
    # when the request is fully handled, have the file deleted
    if isinstance(bundle_analysis_report, BundleAnalysisReport):
        context[
            "request"
        ].bundle_analysis_head_report_db_path = bundle_analysis_report.report.db_path

    context["commit"] = commit

    return bundle_analysis_report
```


Option 2: just need to add a decorator to each resolver that access `info.context` but it is very hard to trace back to what the typed dict should look like
```

# some lib file

from typing import Callable
from functools import wraps
from typing import TypedDict, cast

class ContextDict(TypedDict):
    commit: Commit

def with_typed_context(func: Callable):
    @wraps(func)
    def wrapper(commit: Commit, info: GraphQLResolveInfo, *args, **kwargs):
        # Cast the info.context to ContextDict before calling the original resolver function
        context: ContextDict = cast(ContextDict, info.context)
        # Call the original function with the context being typed
        return func(commit, info, *args, **kwargs)

    return wrapper



# some resolver file

from lib import with_typed_context

@sentry_sdk.trace
@commit_coverage_analytics_bindable.field("components")
@sync_to_async
@with_typed_context
def resolve_coverage_components(commit: Commit, info, filters=None) -> List[Component]:
    info.context["component_commit"] = commit
    current_owner = info.context["request"].current_owner
    all_components = components_service.commit_components(commit, current_owner)

    if filters and filters.get("components"):
        return components_service.filter_components_by_name(
            all_components, filters["components"]
        )

    return all_components
```

After doing testing it doesn't seem like mypy is very helpful in finding obviously wrongly typed usages. So I wouldn't count on this to catch errors, at best this is `info.context` typed dict is only for developer reference when coding, not sure how useful that is..
Scanning the repo, it looks like we have about 8-10 unique key/values where we store our custom stuff in.

At this point my recommendation is to document all the usages of these custom values, if it looks trivial we will just keep the documentation as a reference for future uses. However if documenting this is not feasible because it is so complicated then we can come back to explore further a programmatic solution.

**Comment by suejung-sentry** [comment]
@JerrySentry - this review is amazing!! Yeah that's too bad there aren't any easy fixes there but I think the results of this review alone are great to further our understanding. If there are quick wins on the documentation front, that sounds good, per your recommendation. Thank you for looking into it!

**Comment by JerrySentry** [comment]
Follow up work: https://github.com/codecov/engineering-team/issues/2992
