### ISSUE TITLE
[Client] Upgrade plan fixes

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#790]
While testing, we noticed that if your current plan is the team plan, we'd show the offer to move to team plan when trying to cancel, but we didn't show that when you were pro or sentry pro (and you had less than 10 users and had expired trial status). We want to

1. Ensure the cancel page displays team card option for pro/sentry plans, and not show it when you're currently in the team card (and show the 30% discount card if appropriate). 
2. Change the copy on the card to this: `We'd like to introduce you to our Team Plan. Enjoy essential features at a reduced cost, tailored for those who still want value without the full commitment of our pro offering.`

**Comment by RulaKhaled** [comment]
Quick observation after investigation: 
1. Plan is already showing for pro/sentry plans using `shouldDisplayTeamCard`
2. we're handling the check for `> 10 users` in the API

I'll work on the copy changes and the check if the current plan is on team plan. 
@adrian-codecov if you've seen otherwise while testing, please reach out and let's walk through this together
